# Generated by Django 4.2.dev20220818190229 on 2022-08-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoroPlan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
